<a href="https://colab.research.google.com/github/vani-3883/Vanisha/blob/master/MovieRecommendation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
movies=pd.read_csv('/content/movies_data.csv')

In [ ]:
movies.head()

genres  ...                                     title
0  [{'id': 14, 'name': 'Fantasy'}, {'id': 35, 'na...  ...                                  Reckless
1  [{'id': 10749, 'name': 'Romance'}, {'id': 12, ...  ...                      Girl in the Cadillac
2                [{'id': 99, 'name': 'Documentary'}]  ...  The Haunted World of Edward D. Wood, Jr.
3                [{'id': 99, 'name': 'Documentary'}]  ...    Carmen Miranda: Bananas Is My Business
4                      [{'id': 18, 'name': 'Drama'}]  ...                  Other Voices Other Rooms

[5 rows x 4 columns]

In [ ]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30141 entries, 0 to 30140
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   genres    30141 non-null  object
 1   id        30141 non-null  int64 
 2   overview  29640 non-null  object
 3   title     30140 non-null  object
dtypes: int64(1), object(3)
memory usage: 942.0+ KB


In [ ]:
movies.dropna(inplace = True)

In [ ]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 29639 entries, 0 to 30139
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   genres    29639 non-null  object
 1   id        29639 non-null  int64 
 2   overview  29639 non-null  object
 3   title     29639 non-null  object
dtypes: int64(1), object(3)
memory usage: 1.1+ MB


In [ ]:
new_movies=movies["genres"].str.split("}", n = 1, expand = True) 

In [ ]:
new_movies.head()

0                                                  1
0      [{'id': 14, 'name': 'Fantasy'  , {'id': 35, 'name': 'Comedy'}, {'id': 18, 'na...
1   [{'id': 10749, 'name': 'Romance'  , {'id': 12, 'name': 'Adventure'}, {'id': 80, ...
2  [{'id': 99, 'name': 'Documentary'                                                  ]
3  [{'id': 99, 'name': 'Documentary'                                                  ]
4        [{'id': 18, 'name': 'Drama'                                                  ]

In [ ]:
movies['new_genres']=new_movies[0]

In [ ]:
movies

genres  ...                         new_genres
0      [{'id': 14, 'name': 'Fantasy'}, {'id': 35, 'na...  ...      [{'id': 14, 'name': 'Fantasy'
1      [{'id': 10749, 'name': 'Romance'}, {'id': 12, ...  ...   [{'id': 10749, 'name': 'Romance'
2                    [{'id': 99, 'name': 'Documentary'}]  ...  [{'id': 99, 'name': 'Documentary'
3                    [{'id': 99, 'name': 'Documentary'}]  ...  [{'id': 99, 'name': 'Documentary'
4                          [{'id': 18, 'name': 'Drama'}]  ...        [{'id': 18, 'name': 'Drama'
...                                                  ...  ...                                ...
30135  [{'id': 53, 'name': 'Thriller'}, {'id': 80, 'n...  ...     [{'id': 53, 'name': 'Thriller'
30136  [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...  ...        [{'id': 18, 'name': 'Drama'
30137  [{'id': 18, 'name': 'Drama'}, {'id': 53, 'name...  ...        [{'id': 18, 'name': 'Drama'
30138                [{'id': 99, 'name': 'Documentary'}]  ...  [{'id': 99, 'name': 'Documentary'
30139  [{'id': 36, 'name': 'History'}, {'id': 99, 'na...  ...      [{'id': 36, 'name': 'History'

[29639 rows x 5 columns]

In [ ]:
movies.drop(columns=['genres'])

id  ...                         new_genres
0       58372  ...      [{'id': 14, 'name': 'Fantasy'
1      278939  ...   [{'id': 10749, 'name': 'Romance'
2       73183  ...  [{'id': 99, 'name': 'Documentary'
3      255546  ...  [{'id': 99, 'name': 'Documentary'
4       64562  ...        [{'id': 18, 'name': 'Drama'
...       ...  ...                                ...
30135  131074  ...     [{'id': 53, 'name': 'Thriller'
30136   95046  ...        [{'id': 18, 'name': 'Drama'
30137  305943  ...        [{'id': 18, 'name': 'Drama'
30138  137619  ...  [{'id': 99, 'name': 'Documentary'
30139  136058  ...      [{'id': 36, 'name': 'History'

[29639 rows x 4 columns]

In [ ]:
rating=pd.read_csv("/content/ratings.csv")

In [ ]:
#df=pd.concat([movies,rating])

In [ ]:
#df

In [ ]:
rating.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100004 entries, 0 to 100003
Data columns (total 3 columns):
 #   Column   Non-Null Count   Dtype  
---  ------   --------------   -----  
 0   userId   100004 non-null  int64  
 1   movieId  100004 non-null  int64  
 2   rating   100004 non-null  float64
dtypes: float64(1), int64(2)
memory usage: 2.3 MB


In [ ]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 29639 entries, 0 to 30139
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   genres      29639 non-null  object
 1   id          29639 non-null  int64 
 2   overview    29639 non-null  object
 3   title       29639 non-null  object
 4   new_genres  29639 non-null  object
dtypes: int64(1), object(4)
memory usage: 1.4+ MB


In [ ]:
movies=movies.reset_index(drop=True)
movies["id"] = pd.to_numeric(movies["id"])

In [ ]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29639 entries, 0 to 29638
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   genres      29639 non-null  object
 1   id          29639 non-null  int64 
 2   overview    29639 non-null  object
 3   title       29639 non-null  object
 4   new_genres  29639 non-null  object
dtypes: int64(1), object(4)
memory usage: 1.1+ MB


In [ ]:
df_merge = pd.merge(movies, rating, left_on='id', right_on='movieId')

In [ ]:



df_merge

genres  ...  rating
0      [{'id': 10770, 'name': 'TV Movie'}, {'id': 12,...  ...     3.5
1      [{'id': 12, 'name': 'Adventure'}, {'id': 16, '...  ...     5.0
2      [{'id': 12, 'name': 'Adventure'}, {'id': 16, '...  ...     5.0
3      [{'id': 12, 'name': 'Adventure'}, {'id': 16, '...  ...     5.0
4      [{'id': 12, 'name': 'Adventure'}, {'id': 16, '...  ...     5.0
...                                                  ...  ...     ...
40410  [{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...  ...     3.5
40411  [{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...  ...     2.5
40412  [{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...  ...     0.5
40413  [{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...  ...     1.0
40414  [{'id': 80, 'name': 'Crime'}, {'id': 9648, 'na...  ...     2.0

[40415 rows x 8 columns]

In [ ]:
df1=df_merge["new_genres"].str.split(":", n = 2, expand = True) 

In [ ]:
df1

0               1             2
0      [{'id'   10770, 'name'    'TV Movie'
1      [{'id'      12, 'name'   'Adventure'
2      [{'id'      12, 'name'   'Adventure'
3      [{'id'      12, 'name'   'Adventure'
4      [{'id'      12, 'name'   'Adventure'
...       ...             ...           ...
40410  [{'id'      18, 'name'       'Drama'
40411  [{'id'      18, 'name'       'Drama'
40412  [{'id'      18, 'name'       'Drama'
40413  [{'id'      18, 'name'       'Drama'
40414  [{'id'      80, 'name'       'Crime'

[40415 rows x 3 columns]

In [ ]:
df2=df1[2].str.split("'", n = 2, expand = True) 

In [ ]:
df2

0          1 2 
0          TV Movie   
1         Adventure   
2         Adventure   
3         Adventure   
4         Adventure   
...   ..        ... ..
40410         Drama   
40411         Drama   
40412         Drama   
40413         Drama   
40414         Crime   

[40415 rows x 3 columns]

In [ ]:
df_merge['Genres']=df2[1]


In [ ]:
df_merge

genres  ...     Genres
0      [{'id': 10770, 'name': 'TV Movie'}, {'id': 12,...  ...   TV Movie
1      [{'id': 12, 'name': 'Adventure'}, {'id': 16, '...  ...  Adventure
2      [{'id': 12, 'name': 'Adventure'}, {'id': 16, '...  ...  Adventure
3      [{'id': 12, 'name': 'Adventure'}, {'id': 16, '...  ...  Adventure
4      [{'id': 12, 'name': 'Adventure'}, {'id': 16, '...  ...  Adventure
...                                                  ...  ...        ...
40410  [{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...  ...      Drama
40411  [{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...  ...      Drama
40412  [{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...  ...      Drama
40413  [{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...  ...      Drama
40414  [{'id': 80, 'name': 'Crime'}, {'id': 9648, 'na...  ...      Crime

[40415 rows x 9 columns]

In [ ]:

df_merge.drop(columns=['genres'])

id  ...     Genres
0      97593  ...   TV Movie
1       1260  ...  Adventure
2       1260  ...  Adventure
3       1260  ...  Adventure
4       1260  ...  Adventure
...      ...  ...        ...
40410  40826  ...      Drama
40411  40826  ...      Drama
40412  40826  ...      Drama
40413  64116  ...      Drama
40414   6103  ...      Crime

[40415 rows x 8 columns]

In [ ]:


df_final=df_merge.drop(columns=['new_genres','genres'])

In [ ]:
df_final

id  ...     Genres
0      97593  ...   TV Movie
1       1260  ...  Adventure
2       1260  ...  Adventure
3       1260  ...  Adventure
4       1260  ...  Adventure
...      ...  ...        ...
40410  40826  ...      Drama
40411  40826  ...      Drama
40412  40826  ...      Drama
40413  64116  ...      Drama
40414   6103  ...      Crime

[40415 rows x 7 columns]

In [ ]:
y=df_final['rating']

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [ ]:
model2=LinearRegression()

In [ ]:
train_test_split?

In [ ]:

from sklearn.preprocessing import LabelEncoder

In [ ]:
import numpy as np

In [ ]:
df_final["Genres"] = df_final["Genres"].replace(np.nan, 'none', regex=True)

In [ ]:

le=LabelEncoder()

In [ ]:
df_final["Genres"] = le.fit_transform(df_final["Genres"])

In [ ]:
le.classes_

array(['Action', 'Adventure', 'Animation', 'Comedy', 'Crime',
       'Documentary', 'Drama', 'Family', 'Fantasy', 'Foreign', 'History',
       'Horror', 'Music', 'Mystery', 'Romance', 'Science Fiction',
       'TV Movie', 'Thriller', 'War', 'Western', 'none'], dtype=object)

In [ ]:
x=df_final['Genres'].values.reshape(-1, 1)

In [ ]:
y=df_final['rating'].values.reshape(-1, 1).astype(int)

In [ ]:
X1_train, X1_test, y1_train, y1_test = train_test_split(
...     x, y, test_size=0.33, random_state=42)

In [ ]:
model2.fit(X1_train,y1_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
y2_pred=model2.predict(X1_test)
y2_pred.astype(int)

array([[3],
       [3],
       [3],
       ...,
       [3],
       [3],
       [3]])

In [ ]:
import re  
import nltk  
nltk.download('stopwords') 
from nltk.corpus import stopwords 
from nltk.stem.porter import PorterStemmer

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
corpus = []  
for i in range(0, 40415):  

    review = re.sub('[^a-zA-Z]', ' ', df_final['overview'][i])  
    
    review = review.lower()  
    review = review.split()  

    ps = PorterStemmer()  
      
    # loop for stemming each word 
    # in string array at ith row     
    review = [ps.stem(word) for word in review 
                if not word in set(stopwords.words('english'))]  
                  
    # rejoin all string array elements 
    # to create back into a string 
    review = ' '.join(review)   
      
    # append each string to create 
    # array of clean text  
    corpus.append(review)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer 

cv = CountVectorizer(max_features = 1500)  
  
# X contains corpus (dependent variable) 
X = cv.fit_transform(corpus).toarray() 

In [ ]:
X1=df_final['Genres'].values.flatten()

In [ ]:
X1.size

40415

In [ ]:
X.size

60622500

In [ ]:
y=df_final['rating'].astype(int)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
...     X, y, test_size=0.33, random_state=42)

In [ ]:
from sklearn.ensemble import RandomForestClassifier 
  
# n_estimators can be said as number of 
# trees, experiment with n_estimators 
# to get better results  
model = RandomForestClassifier(n_estimators = 501, 
                            criterion = 'entropy') 
                              
model.fit(X_train, y_train) 

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=501,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
y_pred = model.predict(X_test) 
  

In [ ]:
y_pred.reshape(-1,1)

array([[4],
       [3],
       [4],
       ...,
       [4],
       [4],
       [4]])

In [ ]:
y2_pred.reshape(-1,1)

array([[3.49473139],
       [3.47085436],
       [3.49473139],
       ...,
       [3.48677238],
       [3.38330529],
       [3.48677238]])

In [ ]:
arr = np.column_stack((y_pred,y2_pred))

In [ ]:
Xfinal= pd.DataFrame(data=arr, columns=["column1", "column2"])

In [ ]:
Xfinal

column1   column2
0          4.0  3.494731
1          3.0  3.470854
2          4.0  3.494731
3          4.0  3.446977
4          3.0  3.446977
...        ...       ...
13332      3.0  3.446977
13333      4.0  3.446977
13334      4.0  3.486772
13335      4.0  3.383305
13336      4.0  3.486772

[13337 rows x 2 columns]

In [ ]:
Xfinal_train, Xfinal_test, yfinal_train, yfinal_test = train_test_split(
...     Xfinal, y_test, test_size=0.33, random_state=42)

In [ ]:
model_final=LinearRegression()

In [ ]:
model_final.fit(Xfinal_train,yfinal_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
Yfinal_pred=model_final.predict(Xfinal_test)

In [ ]:
Yfinal_pred.astype(int)

array([2, 3, 3, ..., 3, 3, 3])

In [ ]:
pd.DataFrame(Yfinal_pred).to_csv('pred_final.csv')